version: '3'
services:
  postgres:
    image: postgres:13.2
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gjg-test-task
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - gjg-test-task_pgdata:/var/lib/postgresql/data
  runner:
    stdin_open: true
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./migrations:/migrations
volumes:
  gjg-test-task_pgdata:
    external: true